(function () {
  const root = document.documentElement;
  const languageButton = document.querySelector("[data-language-toggle]");
  const nav = document.querySelector(".main-nav");
  const navToggle = document.querySelector(".nav-toggle");
  const originalTitle = document.title;
  let currentLanguage = "zh-CN";
  let refreshing = false;

  const exact = {
    "视觉原型": "Visual prototype",
    "用于比较首页信息层级，不是正式网站": "A visual prototype for comparing homepage information hierarchy; not the production site.",
    "首页": "Home",
    "研究与成果": "Research & outcomes",
    "合作单位": "Partner centers",
    "队列信息": "Cohort",
    "项目文件": "Documents",
    "菜单": "Menu",
    "发起科研合作": "Start a research collaboration",
    "全国临床研究力量": "Clinical research strength across China",
    "全国多中心临床研究协作网络": "A national multicenter clinical research network",
    "从每一次临床观察出发，": "Starting from every clinical observation, ",
    "共同寻找": "we work together to find",
    "危重症的答案": " answers for critical illness",
    "A — 人文叙事": "A — Human narrative",
    "B — 学术编辑部": "B — Academic editorial",
    "C — 队列数据优先": "C — Cohort data first",
    "A — 研究图谱": "A — Research atlas",
    "B — 研究浏览器": "B — Research explorer",
    "C — 证据矩阵": "C — Evidence matrix",
    "A — 队列总览": "A — Cohort overview",
    "B — 数据仪表盘": "B — Data dashboard",
    "C — 队列叙事": "C — Cohort narrative",
    "4 条研究主线展示重点成果 · 页尾汇总 2022–2026 年 17 篇代表性论文": "Four research tracks with selected evidence · 17 representative papers from 2022–2026 in the publication ledger",
    "让每一项成果，": "Make every finding",
    "回到它所回答的": "return to the ",
    "主中心成员": "Coordinating-center members",
    "分中心成员": "Branch-center members",
    "成员资料来源：主中心与分中心成员表 · 当前状态 approved": "Source: coordinating-center and branch-center member rosters · Current status: approved",
    "复旦大学附属中山医院副院长、急诊科副主任（主持工作）；上海市应急救援与急危重症研究所所长，上海市急危重症临床研究中心主任；急诊医学主任医师、教授、博士研究生导师。": "Vice President of Zhongshan Hospital, Fudan University and Acting Deputy Director of Emergency Medicine; Director of the Shanghai Institute of Emergency Rescue and Critical Care and the Shanghai Clinical Research Center for Emergency and Critical Care; Chief Physician, Professor, and Doctoral Supervisor in Emergency Medicine.",
    "从临床到基础，再到数据与智能": "From clinical care to basic science, data, and intelligence",
    "主中心下属团队": "Coordinating-center teams",
    "个团队 · 51 名成员 · 6 位教授": " teams · 51 members · 6 professors",
    "正在从静态 JSON 读取主中心成员资料……": "Loading coordinating-center member profiles from static JSON…",
    "王瑞兰教授": "Professor Wang Ruilan",
    "何征宇教授": "Professor He Zhengyu",
    "詹丽英教授": "Professor Zhan Liying",
    "邓医宇教授": "Professor Deng Yiyu",
    "张召才教授": "Professor Zhang Zhaocai",
    "谈定玉教授": "Professor Tan Dingyu",
    "临床问题": "clinical question",
    "围绕 ARDS、脓毒症与多器官功能障碍的异质性，SEARCH 将研究问题、队列方法和代表成果连接成一条可追溯的证据路径。": "Around the heterogeneity of ARDS, sepsis, and multiorgan dysfunction, SEARCH connects research questions, cohort methods, and selected evidence into a traceable pathway.",
    "研究主线": "Research tracks",
    "当前代表论文": "Selected papers",
    "论文不再集中堆叠，而是陈列在它所支撑的研究方向之中。": "Papers are not stacked in isolation; they are presented within the research directions they support.",
    "ARDS 炎症表型": "ARDS inflammatory phenotypes",
    "免疫与代谢重塑": "Immune & metabolic remodeling",
    "多模态早期预警": "Multimodal early warning",
    "多中心转化验证": "Multicenter translation",
    "融合临床表型、血清蛋白组、胸部影像及随访结局，并结合肺损伤机制研究。": "Combine clinical phenotypes, serum proteomics, chest imaging, follow-up outcomes, and lung-injury biology.",
    "识别可重复的生物学亚型，为糖皮质激素、PEEP 与修复策略评价提供依据。": "Identify reproducible biological subtypes to inform evaluation of corticosteroids, PEEP, and repair strategies.",
    "解析关键免疫细胞、RNA 修饰、细胞因子通路与临床治疗暴露之间的联系。": "Map the links among key immune cells, RNA modifications, cytokine pathways, and clinical treatment exposures.",
    "寻找可干预的免疫通路，并识别治疗获益与风险并存的人群。": "Identify actionable immune pathways and patient groups in whom treatment benefit and risk coexist.",
    "联合临床、实验室、影像和多组学数据，构建可解释且可外部验证的模型。": "Combine clinical, laboratory, imaging, and multi-omics data to build interpretable models that can be externally validated.",
    "将复杂生物信息转化为可在临床场景中使用的风险分层工具。": "Translate complex biological information into risk-stratification tools for clinical use.",
    "单中心发现能否在不同地区、患者结构和临床流程中保持稳定？": "Can single-center findings remain stable across regions, patient populations, and clinical workflows?",
    "统一入组、采样、数据字典与质量控制，在真实世界协作网络中重复验证。": "Standardize enrollment, sampling, data dictionaries, and quality control, then replicate findings in a real-world collaboration network.",
    "形成可比较、可追溯、可推广的临床证据，并支持公共卫生与协作研究。": "Build comparable, traceable, and generalizable clinical evidence to support public health and collaborative research.",
    "在四条研究主线之外，集中呈现团队近五年的代表性论文，作为持续研究工作的年度总表。": "Alongside the four research tracks, this ledger presents the team's representative papers from the past five years as an annual record of continuing work.",
    "涉及期刊": "Journals represented",
    "各年度代表性论文数量": "Representative papers by year",
    "来源：团队提供的《代表性论文》文档及新增中文期刊文章；按 2022–2026 年筛选，共 17 篇。页面不展示期刊影响因子。": "Source: the team's Representative Publications document plus the newly added Chinese journal article; 17 papers selected from 2022–2026. Journal impact factors are not displayed.",
    "血清生物标志物联合检测在急性呼吸窘迫综合征诊断和预后预测中的价值": "The value of combined serum biomarkers detection in the diagnosis and prognosis prediction of acute respiratory distress syndrome",
    "孙健、孙湛、杨依霖、宋振举、徐斐翔": "Sun Jian, Sun Zhan, Yang Yilin, Song Zhenju, Xu Feixiang",
    "中华急诊医学杂志": "Chinese Journal of Emergency Medicine",
    "提出临床问题": "Define a clinical question",
    "从诊疗困境与治疗反应差异中定义问题。": "Define questions from care challenges and differences in treatment response.",
    "建立规范队列": "Build a standardized cohort",
    "统一入组、采样、随访与质量控制。": "Standardize enrollment, sampling, follow-up, and quality control.",
    "解析疾病机制": "Study disease mechanisms",
    "融合临床、影像和多组学信息。": "Integrate clinical, imaging, and multi-omics information.",
    "开展外部验证": "Conduct external validation",
    "回到多中心临床环境检验稳定性。": "Return to multicenter clinical settings to test stability.",
    "研究不是论文的目录，": "Research is not a paper index,",
    "而是问题持续演进的记录。": "but a record of questions evolving over time.",
    "研究方向与成果": "Research directions & outcomes",
    "一张图读懂": "Read the structure at a glance",
    "横向比较每条研究主线的问题、方法和代表论文，适合快速判断团队的研究结构与合作切入点。": "Compare the questions, methods, and representative papers across tracks to understand the team's structure and identify points for collaboration.",
    "让公开文件清晰可查，": "Make public documents clear and searchable,",
    "集中整理 SEARCH 主中心与分中心经审核可公开的项目文件，为科研合作、中心沟通和规范执行提供统一入口。": "This library organizes reviewed, publishable project documents from SEARCH coordinating and branch centers, providing one entry point for research collaboration, center communication, and protocol implementation.",
    "当前提供主中心已确认文件 · 分中心文件待补充": "Confirmed coordinating-center files available · Branch-center files pending",
    "文件待补充": "Files pending",
    "下载与使用说明": "Download and use guidance",
    "本页面只呈现经团队确认可公开的项目级文件，不包含个体级临床数据、内部工作记录或未经审核的材料。": "This page presents only project-level documents confirmed for public release; it contains no individual clinical data, internal work records, or unreviewed materials.",
    "核对版本": "Check the version",
    "下载前请确认文件名称、版本编号及更新日期。": "Confirm the filename, version number, and update date before downloading.",
    "规范使用": "Use appropriately",
    "文件用于了解项目流程与开展合规的科研协作。": "Use these files to understand project procedures and conduct compliant research collaboration.",
    "持续补充": "Ongoing additions",
    "新增公开文件完成审核后，将按所属中心加入本页面。": "New public files will be added under the relevant center after review.",
    "由复旦大学附属中山医院统筹，主中心与全国分中心共同完成队列建设、病例入组、样本采集、数据核对与研究验证。每一家机构都不是名单中的一个名称，而是长期协作中的一份责任。": "Coordinated by Zhongshan Hospital, Fudan University, the coordinating center and branch centers jointly build the cohort, enroll participants, collect samples, check data, and validate findings. Each institution is more than a name on a list: it represents a long-term responsibility within the collaboration.",
    "以共同标准连接": "Connected by shared standards",
    "负责研究方案统筹、统一标准建设、跨中心协调和成果整合，是全国协作网络的共同连接点。": "The coordinating center oversees protocols, shared standards, cross-center coordination, and evidence integration—the common connection point for the national network.",
    "SEARCH 协调与研究主中心": "SEARCH coordinating and research center",
    "多中心研究方案与执行标准统筹": "Multicenter protocol and implementation standards",
    "临床队列、生物样本与研究质量协同": "Clinical cohort, biospecimen, and research-quality coordination",
    "研究发现整合、验证与科研合作沟通": "Evidence integration, validation, and research collaboration",
    "项目负责人": "Project lead",
    "正在从静态 JSON 读取机构与成员资料……": "Loading centers and member profiles from static JSON…",
    "此页面需要启用 JavaScript 才能展开中心成员。": "JavaScript is required to expand center members on this page.",
    "按区域筛选分中心": "Filter branch centers by region",
    "负责研究方案统筹、统一标准建设、跨中心协调和成果整合，是全国协作网络的共同连接点。": "The coordinating center oversees protocols, shared standards, cross-center coordination, and evidence integration—the common connection point for the national network.",
    "由共同标准连接的临床研究团队": "A clinical research team connected by shared standards",
    "以统一的入组、采样与质量标准连接主中心和全国分中心。这里呈现的是经确认可公开的队列聚合信息，不包含任何个体级临床记录。": "The coordinating center and branch centers are connected by shared enrollment, sampling, and quality standards. This page presents confirmed, publishable aggregate cohort information and contains no individual-level clinical records.",
    "截至 2026-07-02 的静态数据 · 生物样本按中心拆分待补充": "Static data as of 2026-07-02 · Center-level biospecimen split pending",
    "同一统计截止日期下，分别呈现主中心和分中心入组人数，确保不同层级的数据口径清晰可比。": "Using the same cutoff date, enrollment is shown separately for the coordinating center and branch centers so that figures at each level remain clear and comparable.",
    "承担队列统筹、统一标准建设、跨中心协调与研究质量管理。": "Oversee cohort coordination, shared standards, cross-center coordination, and research quality.",
    "按照共同研究方案持续完成入组、采样、数据核对与外部验证。": "Continue enrollment, sampling, data checks, and external validation under the shared protocol.",
    "包括血清、血浆、PBMC 等实体样本。同一位受试者可能对应多管样本，因此该数字不等同于入组人数。": "Includes physical serum, plasma, PBMC, and other samples. One participant may contribute multiple tubes, so this number is not equivalent to enrollment.",
    "主中心样本管数": "Coordinating-center tubes",
    "分中心样本管数": "Branch-center tubes",
    "当前已确认总量，尚未提供中心拆分": "The confirmed total is available; center-level split has not been provided",
    "使用已确认的聚合数字完成页面设计。": "Use confirmed aggregate figures for the page design.",
    "团队审核": "Team review",
    "核对中心拆分、统计日期与公开权限。": "Check center-level splits, dates, and public-release permissions.",
    "公开发布": "Public release",
    "静态审核数据": "Statically reviewed data",
    "当前阶段": "Current stage",
    "当前视觉方向": "Current visual direction",
    "公开数据确认": "Public data confirmed",
    "页面视觉设计": "Page visual design",
    "中心样本拆分": "Center-level sample split",
    "后续阶段": "Later phase",
    "中心拆分待补充": "Center-level split pending",
    "不以推算值替代正式审核数据": "Estimates do not replace formally reviewed data",
    "读懂数字背后的队列": "Reading the cohort behind the numbers",
    "先让每个数字经得起核对，": "First make every figure verifiable,",
    "再让更新变得自动。": "then make updates automatic.",
    "一份面向科研合作者的队列资源简报。每一个公开数字，都对应明确的统计口径、中心层级与审核日期。": "A cohort resource brief for research collaborators. Every public figure has a defined metric, center level, and review date.",
    "已按研究方案纳入临床研究队列的受试者总人数。": "Total participants enrolled in the clinical cohort under the study protocol.",
    "复旦大学附属中山医院主中心入组人数。": "Enrollment at the coordinating center, Zhongshan Hospital, Fudan University.",
    "全国协作分中心入组人数合计。": "Total enrollment across national branch centers.",
    "血清、血浆、PBMC 等实体生物样本管数总计。": "Total tubes of physical serum, plasma, PBMC, and other biospecimens.",
    "未知数据明确留白": "Leave unknown data blank",
    "样本按中心拆分尚未提供，因此页面保留“待补充”，不以估算值填补正式统计。": "Center-level sample splits are not yet available, so the page retains “pending” rather than filling official figures with estimates.",
    "探索研究与成果": "Explore research & outcomes",
    "认识协作团队": "Meet the collaborative team",
    "查看全国合作单位": "View all partner centers",
    "查看完整研究图谱": "View the full research atlas",
    "查看研究与成果 →": "View research & outcomes →",
    "查看合作单位 →": "View partner centers →",
    "查看队列数据": "View cohort data",
    "下载": "Download",
    "ICU 多学科团队在床旁共同讨论": "Multidisciplinary ICU team discussing care at the bedside",
    "ECMO 团队共同检查循环管路与设备": "ECMO team checking the circuit and equipment together",
    "ICU 夜班医护人员协同开展床旁工作": "Night-shift ICU staff coordinating bedside care",
    "查看 ICU 多学科协作场景": "View the multidisciplinary ICU collaboration scene",
    "查看 ECMO 团队协作场景": "View the ECMO team collaboration scene",
    "查看 ICU 夜班照护场景": "View the ICU night-shift care scene",
    "临床问题不是研究的终点，而是协作的起点": "A clinical question is not the end of research; it is the beginning of collaboration.",
    "研究问题不是研究的终点，而是协作的起点": "A research question is not the endpoint; it is the starting point for collaboration.",
    "我们相信，只有把不同医院、不同学科和不同数据层次真正连接起来，才能看见 ARDS 与脓毒症背后的异质性。": "We believe that only by truly connecting hospitals, disciplines, and layers of data can we see the heterogeneity behind ARDS and sepsis.",
    "SEARCH 联结临床一线、标准化队列、生物样本库与多组学研究，让来自不同中心的问题和证据汇聚成可验证、可转化的研究发现。": "SEARCH connects frontline clinical care, standardized cohorts, biobanks, and multi-omics research, bringing questions and evidence from different centers together into findings that can be verified and translated into care.",
    "主中心与全国分中心共同完成病例入组、样本采集、长期随访和临床验证。每一份数据都来自规范流程，每一项发现都需要回到真实临床场景接受检验。": "The coordinating center and branch centers jointly conduct enrollment, sampling, long-term follow-up, and clinical validation. Every data point comes from a standardized process, and every finding must return to real clinical settings for testing.",
    "主中心与分中心": "Coordinating and branch centers",
    "从研究问题到代表成果": "From research questions to selected evidence",
    "ARDS 炎症分型": "ARDS inflammatory phenotypes",
    "融合蛋白组、影像和临床表型，识别具有不同预后与治疗反应的生物学亚型。": "We integrate proteomics, imaging, and clinical phenotypes to identify biological subtypes with different outcomes and treatment responses.",
    "表型识别": "Phenotype discovery",
    "脓毒症免疫失衡": "Sepsis immune dysregulation",
    "追踪感染、免疫代谢与器官损伤之间的动态关系，寻找可干预通路。": "We trace the dynamic relationship between infection, immunometabolism, and organ injury to identify actionable pathways.",
    "机制发现": "Mechanism discovery",
    "多模态风险预测": "Multimodal risk prediction",
    "将临床、影像、实验室与组学特征转化为可验证的早期预警模型。": "We translate clinical, imaging, laboratory, and omics features into verifiable early-warning models.",
    "临床转化": "Clinical translation",
    "精准干预评价": "Precision intervention evaluation",
    "在多中心真实世界数据中评价不同亚型的治疗反应与长期结局。": "We evaluate treatment response and long-term outcomes across subtypes using multicenter real-world data.",
    "证据验证": "Evidence validation",
    "由共同标准连接的临床研究团队": "A clinical research team connected by shared standards",
    "SEARCH 汇聚急诊、重症、呼吸、影像与组学研究者，以共同标准和彼此信任连接全国多中心。每一次讨论、采样与数据核对，都凝聚着临床一线的坚持，也让研究回到改善危重症患者结局的共同愿望。首页呈现六位 PI，完整成员可在“合作单位”中查看。": "SEARCH brings together researchers in emergency medicine, critical care, respiratory medicine, imaging, and omics. Shared standards and mutual trust connect centers across the country. Every discussion, sample, and data check reflects the persistence of frontline care and returns research to a shared goal: improving outcomes for critically ill patients. Six principal investigators are introduced here; the full membership can be explored under Partner centers.",
    "了解合作网络": "Explore the partner network",
    "从床旁问题出发，": "Starting with bedside questions,",
    "共同推进脓毒症与 ARDS 研究。": "we advance sepsis and ARDS research together.",
    "复旦大学附属中山医院作为 SEARCH 主中心，统筹研究方案、标准化队列与跨中心协作，让每一个临床问题都能沿着可追溯的路径走向可验证的答案。": "As the SEARCH coordinating center, Zhongshan Hospital, Fudan University, coordinates study protocols, standardized cohorts, and cross-center collaboration—helping every clinical question move along a traceable path toward a verifiable answer.",
    "宋振举教授": "Professor Song Zhenju",
    "SEARCH 项目总负责人 · 复旦大学附属中山医院主中心 PI": "SEARCH principal investigator · Coordinating-center PI, Zhongshan Hospital, Fudan University",
    "主中心团队合照预留位置": "Reserved space for the coordinating-center team portrait",
    "团队合照待补充": "Team portrait pending",
    "每一项发现，都有一支团队在背后。": "Behind every finding is a team.",
    "这里将展示主中心团队合照。照片确认后，替换该预留区域即可。": "The coordinating-center team portrait will appear here. Once approved, it can replace this reserved frame directly.",
    "从床旁观察、标准化入组到多中心验证，SEARCH 让临床团队与研究团队在同一个问题上持续同行。": "From bedside observation and standardized enrollment to multicenter validation, SEARCH keeps clinical and research teams moving together around the same question.",
    "查看协作网络": "View the collaboration network",
    "临床数据库患者": "Clinical cohort participants",
    "累计入组人数": "Total enrolled participants",
    "主中心 2,316 · 分中心 955": "Coordinating center 2,316 · Branch centers 955",
    "实体生物样本管": "Biospecimen tubes",
    "血清、血浆、PBMC 等总和": "Serum, plasma, PBMCs, and other specimens",
    "全国合作机构": "Partner institutions nationwide",
    "共同执行标准化研究方案": "Implementing a shared standardized protocol",
    "数据截至": "Data as of",
    "从临床现场出发，推动危重症精准诊疗": "From the clinical front line to precision care for critical illness",
    "临床与科研共同负责": "Clinicians and researchers working together",
    "临床医生、转化研究者、组学与数据科学人员围绕同一临床问题协同工作，让发现能够经得起多中心验证。": "Clinicians, translational researchers, omics specialists, and data scientists work around the same clinical questions so that discoveries can withstand multicenter validation.",
    "一条可追溯的研究路径": "A traceable research pathway",
    "让多中心数据成为危重症研究的共同基础设施": "Making multicenter data shared infrastructure for critical illness research",
    "连接标准化临床队列、生物样本库与多组学研究，为 ARDS、脓毒症及多器官功能障碍提供可验证的科研基础。": "We connect standardized clinical cohorts, biobanks, and multi-omics research to build a verifiable research foundation for ARDS, sepsis, and multiorgan dysfunction.",
    "静态数据 · 截至 2026.07.02": "Static data · as of 2026.07.02",
    "累计入组": "Total enrolled",
    "主中心": "Coordinating center",
    "分中心": "Branch centers",
    "生物样本": "Biospecimens",
    "合作机构": "Partner institutions",
    "中心样本分布": "Biospecimen distribution by center",
    "待核对": "Pending verification",
    "主中心 / 分中心拆分数据尚未确认": "The coordinating-center / branch-center split has not yet been confirmed",
    "临床问题": "Clinical question",
    "从急诊与危重症现场识别未被满足的研究问题。": "Identify unmet research questions in emergency and critical care settings.",
    "队列与样本": "Cohort & samples",
    "以统一方案开展入组、采样、随访和质量控制。": "Conduct enrollment, sampling, follow-up, and quality control under a shared protocol.",
    "多模态研究": "Multimodal research",
    "整合临床、影像、实验室、蛋白组和微生态数据。": "Integrate clinical, imaging, laboratory, proteomic, and microbiome data.",
    "多中心验证": "Multicenter validation",
    "检验研究发现的稳定性、可解释性和临床价值。": "Test the stability, interpretability, and clinical value of research findings.",
    "围绕共同问题，建立规范、开放的科研协作": "Building rigorous, open research collaboration around shared questions",
    "让每一例入组与每一份样本，": "Make every participant and every sample",
    "成为可追溯的": "a traceable ",
    "研究坐标": "research coordinate",
    "SEARCH 以统一的入组、采样与质量标准连接主中心和全国分中心。这里呈现的是经确认可公开的队列聚合信息，不包含任何个体级临床记录。": "SEARCH connects the coordinating center and branch centers through shared enrollment, sampling, and quality standards. This page presents confirmed, publishable aggregate cohort information and contains no individual-level clinical records.",
    "入组总人数": "Total enrolled participants",
    "主中心入组": "Coordinating-center enrollment",
    "分中心入组": "Branch-center enrollment",
    "全国协作分中心合计": "Total across branch centers",
    "实体生物样本管数": "Biospecimen tubes",
    "血清、血浆、PBMC 等总计": "Serum, plasma, PBMCs, and other specimens",
    "入组构成": "Enrollment composition",
    "入组人数 ≠ 样本管数": "Participants enrolled ≠ specimen tubes",
    "入组人数统计受试者；实体生物样本管数统计样本库中的样本管，同一受试者可能对应多管样本。": "Enrollment counts participants. Biospecimen tubes count physical samples stored in the biobank; one participant may contribute multiple tubes.",
    "主中心负责队列统筹，分中心按照共同方案参与建设。分层展示让协作贡献与数据来源更加清晰。": "The coordinating center oversees the cohort, while branch centers contribute under a shared protocol. Layered reporting makes contributions and data sources clearer.",
    "从静态审核到可持续更新": "From static review to sustainable updates",
    "当前使用静态审核数据完成设计。未来接入在线同步时，仍保留审核、更新时间和数据口径说明。": "The current design uses statically reviewed data. When online synchronization is introduced, the page will retain review status, update time, and definitions for every figure.",
    "在线同步": "Online synchronization",
    "同步经确认的候选更新数字。": "Synchronize confirmed candidate figures.",
    "后续按同一审核日期统一发布": "Publish consistently under the same review date.",
    "审核通过后更新页面并保留时间戳。": "Update the page after approval and retain a timestamp.",
    "项目文件下载": "Project document downloads",
    "让公开文件清晰可查，": "Make public documents clear and searchable,",
    "让研究协作": "so research collaboration ",
    "有据可循": "has a clear basis",
    "集中整理 SEARCH 主中心与分中心经审核可公开的项目文件，为科研合作、中心沟通和规范执行提供统一入口。": "This library organizes reviewed, publishable project documents from SEARCH coordinating and branch centers, providing one entry point for research collaboration, center communication, and protocol implementation.",
    "按照主中心与分中心分别整理。请在使用前核对文件名称、版本和日期，文件内容以下载版本为准。": "Documents are organized by coordinating center and branch centers. Please verify the filename, version, and date before use; the downloaded file is authoritative.",
    "主中心文件已上线": "Coordinating-center documents are online",
    "当前可下载文件": "Available downloads",
    "已公开文件中心": "Centers with public files",
    "生物样本库伦理批件": "Biobank ethics approval",
    "人类遗传资源保藏中心知情同意书": "Informed consent form for the Human Genetic Resources Preservation Center",
    "下载": "Download",
    "项目联系": "Project contact",
    "科研合作、多中心协作与项目公开资料咨询": "Research collaboration, multicenter coordination, and public project information",
    "相关机构": "Related institutions",
    "网站导航": "Site navigation",
    "科研信息展示 · 不构成医疗建议": "Research information only · Not medical advice",
    "连接临床一线、规范队列、生物样本与多中心研究，共同推动危重症临床证据的发现、验证与转化。": "Connecting frontline care, standardized cohorts, biospecimens, and multicenter research to advance the discovery, validation, and translation of clinical evidence for critical illness.",
    "主中心与分中心合计": "Coordinating and branch centers combined",
    "全国协作分中心": "National branch centers",
    "血清 SERUM": "Serum / SERUM",
    "血浆 PLASMA": "Plasma / PLASMA",
    "其他已入库实体样本": "Other banked specimens",
    "待补充": "Pending addition",
    "PDF · 约 1.5 MB · 主中心文件": "PDF · approx. 1.5 MB · coordinating-center file",
    "PDF · 约 252 KB · V2.1 · 2024-11-14": "PDF · approx. 252 KB · V2.1 · 2024-11-14",
    "29 名公开成员": "29 public members",
    "64 名公开成员": "64 public members",
    "宋振举 教授": "Song Zhenju · Professor",
    "炎症表型": "inflammatory phenotypes",
    "人": "participants",
    "成员资料来源：分中心成员表 · 当前状态 approved": "Source: branch-center member roster · Current status: approved",
    "主中心完整成员资料尚未整理，当前仅展示已确认负责人。": "Complete coordinating-center member data are still being organized; only the confirmed lead is shown for now.",
    "研究与成果 · SEARCH": "Research & outcomes · SEARCH",
    "合作单位 · SEARCH": "Partner centers · SEARCH",
    "队列信息 · SEARCH": "Cohort · SEARCH",
    "项目文件 · SEARCH": "Documents · SEARCH",
    "近五年代表性论文总览": "Five-year publication overview",
    "展开论文总表": "Open publication ledger",
    "收起论文总表": "Close publication ledger",
    "从床旁问题到可验证证据": "From bedside questions to verifiable evidence",
    "论文是研究路径上的阶段性证据，而不是孤立的成果清单。": "Papers are staged evidence along a research pathway, not an isolated list of achievements.",
    "选择一个研究方向，集中浏览它的研究问题、方法与代表证据。": "Choose a research direction to explore its questions, methods, and selected evidence.",
    "代表性论文": "Selected publications",
    "代表成果": "Selected evidence",
    "研究问题": "Research question",
    "研究方法": "Methods",
    "研究目标": "Research aim",
    "ARDS 炎症表型与精准通气": "ARDS inflammatory phenotypes & precision ventilation",
    "脓毒症免疫与代谢重塑": "Sepsis immune and metabolic remodeling",
    "多模态早期预警与预后": "Multimodal early warning & prognosis",
    "多中心队列与转化验证": "Multicenter cohorts & translational validation",
    "相似临床诊断背后是否存在不同炎症状态、器官损伤与治疗反应？": "Do similar clinical diagnoses conceal distinct inflammatory states, organ injury patterns, and treatment responses?",
    "感染后的免疫激活与免疫抑制如何共同影响继发感染和器官功能？": "How do post-infectious immune activation and suppression jointly shape secondary infection and organ function?",
    "如何在疾病早期识别高风险患者，并持续判断器官衰竭与治疗反应？": "How can high-risk patients be identified early while organ failure and treatment response are monitored over time?",
    "研究发现能否跨地区、跨中心稳定复现？": "Can research findings be reproduced reliably across regions and centers?",
    "临床表型、血清蛋白组、胸部影像、随访结局与肺损伤机制研究。": "Clinical phenotyping, serum proteomics, chest imaging, follow-up outcomes, and lung-injury biology.",
    "关键免疫细胞、RNA 修饰、细胞因子通路与临床治疗暴露。": "Key immune cells, RNA modifications, cytokine pathways, and clinical treatment exposures.",
    "临床、实验室、影像和多组学数据融合与可解释风险建模。": "Clinical, laboratory, imaging, and multi-omics integration with interpretable risk modeling.",
    "统一入组、采样、数据字典与质量控制，并开展跨中心重复验证。": "Shared enrollment, sampling, data dictionaries, and quality control with cross-center replication.",
    "由复旦大学附属中山医院统筹，主中心与全国分中心共同完成队列建设、病例入组、样本采集、数据核对与研究验证。每一家机构都不是名单中的一个名称，而是长期协作中的一份责任。": "Coordinated by Zhongshan Hospital, Fudan University, the coordinating center and branch centers jointly build the cohort, enroll participants, collect samples, check data, and validate findings. Each institution is more than a name on a list: it represents a long-term responsibility within the collaboration.",
    "让不同中心的数据可以彼此理解": "Making data understandable across centers",
    "多中心研究的价值不仅来自规模，也来自可比较、可追溯和可重复的共同流程。": "The value of multicenter research comes not only from scale, but also from shared processes that are comparable, traceable, and reproducible.",
    "统一数据标准": "Shared data standards",
    "统一变量定义、时间窗口和缺失数据规则，支持跨中心合并分析与质量审查。": "Align variable definitions, time windows, and missing-data rules to support pooled multicenter analysis and quality review.",
    "规范样本流程": "Standardized sample workflows",
    "统一采样、处理、运输和存储标准，让组学结果与临床事件准确对应。": "Align sampling, processing, transport, and storage so that omics results correspond accurately to clinical events.",
    "独立外部验证": "Independent external validation",
    "在不同地区、患者结构和临床流程中验证研究发现的稳定性与实际价值。": "Validate the stability and practical value of findings across regions, patient populations, and clinical workflows.",
    "机构顺序与主中心成员资料仍待最终审核": "Institution order and coordinating-center member data remain subject to final review",
    "机构顺序与成员资料仍待最终审核": "Institution order and member profiles remain subject to final review",
    "分中心相关文件将在完成公开审核后统一补充。": "Branch-center documents will be added after public-release review is complete.",
    "当前阶段": "Current stage",
    "当前为静态审核数据": "Currently based on statically reviewed data",
    "数据截至 2026.07.02": "Data as of 2026.07.02",
    "查看中心成员": "View center members",
    "收起中心成员": "Collapse center members",
    "查看简介": "View profile",
    "成员资料未能载入": "Member data could not be loaded",
    "团队成员": "Team member",
    "分中心 PI": "Branch-center PI",
    "主中心 · MAIN CENTER": "Coordinating center · MAIN CENTER",
    "分中心 · BRANCH CENTERS": "Branch centers · BRANCH CENTERS",
    "项目负责人 · PRINCIPAL INVESTIGATOR": "PRINCIPAL INVESTIGATOR",
    "工作经历": "Professional experience",
    "学科平台任职": "Academic and clinical platform appointments",
    "学术团体任职": "Professional society appointments",
    "急诊科": "Department of Emergency Medicine",
    "主任医师、科室副主任（主持工作）": "Chief Physician and Acting Deputy Director, Department of Emergency Medicine",
    "教授、博士生导师": "Professor and Doctoral Supervisor",
    "副院长": "Vice President",
    "院长": "President",
    "徐汇区中心医院": "Xuhui District Central Hospital",
    "国家临床重点专科（化学应急）": "National Clinical Key Specialty (Chemical Emergency)",
    "负责人": "Program Lead",
    "上海市急危重症临床研究中心": "Shanghai Clinical Research Center for Emergency and Critical Care",
    "复旦大学急危重症研究所": "Fudan University Institute of Emergency Rescue and Critical Care",
    "所长": "Director",
    "上海市肺部炎症与损伤重点实验室": "Shanghai Key Laboratory of Pulmonary Inflammation and Injury",
    "上海市优秀学科带头人": "Shanghai Outstanding Discipline Leader",
    "中华医学会急诊医学分会青年委员会": "Youth Committee, Emergency Medicine Branch, Chinese Medical Association",
    "中国医药教育协会急诊医学专科分会": "Emergency Medicine Specialty Branch, China Medical Education Association",
    "中国医学救援协会生命支持分会": "Life Support Branch, Chinese Medical Rescue Association",
    "上海市医师协会急诊医学分会": "Emergency Medicine Branch, Shanghai Medical Doctor Association",
    "上海市医学会急诊专科分会": "Emergency Medicine Specialty Branch, Shanghai Medical Association",
    "副主任委员": "Vice Chair",
    "副会长": "Vice President",
    "会长": "President",
    "公开成员": "Public members",
    "全部": "All",
    "中部与华南": "Central & South China",
    "浙江与福建": "Zhejiang & Fujian",
    "上海": "Shanghai",
    "江苏": "Jiangsu",
    "复旦大学附属中山医院": "Zhongshan Hospital, Fudan University",
    "复旦中山": "Fudan Zhongshan",
    "复旦大学上海医学院": "Shanghai Medical College, Fudan University",
    "复旦大学": "Fudan University",
    "上海市徐汇区枫林路 180 号": "180 Fenglin Road, Xuhui District, Shanghai",
    "科研信息展示 · 不构成医疗建议": "Research information only · Not medical advice",
  };

  // English display names for members. Chinese mode always restores the original
  // names from the DOM/static JSON; English mode uses this first-pass Pinyin roster.
  const memberNames = {
    "何征宇": "He Zhengyu",
    "余鑫": "Yu Xin",
    "刘奇": "Liu Qi",
    "刘显东": "Liu Xiandong",
    "刘永海": "Liu Yonghai",
    "卢峰": "Lu Feng",
    "吉冉": "Ji Ran",
    "吴学玲": "Wu Xueling",
    "吴永然": "Wu Yongran",
    "周书琴": "Zhou Shuqin",
    "唐传东": "Tang Chuandong",
    "唐伦先": "Tang Lunxian",
    "孙克玉": "Sun Keyu",
    "宋剑峰": "Song Jianfeng",
    "宋振举": "Song Zhenju",
    "宗洪凤": "Zong Hongfeng",
    "张云": "Zhang Yun",
    "张召才": "Zhang Zhaocai",
    "张巍": "Zhang Wei",
    "张琳": "Zhang Lin",
    "彭成朝": "Peng Chengchao",
    "彭沪": "Peng Hu",
    "徐佳宁": "Xu Jianing",
    "施荣": "Shi Rong",
    "曲笑啸": "Qu Xiaoxiao",
    "朱建刚": "Zhu Jiangang",
    "朱景法": "Zhu Jingfa",
    "李家静": "Li Jiajing",
    "李成": "Li Cheng",
    "林思敏": "Lin Simin",
    "林艺延": "Lin Yiyan",
    "沈瑶": "Shen Yao",
    "潘舟": "Pan Zhou",
    "王建李": "Wang Jianli",
    "王日": "Wang Ri",
    "王瑞兰": "Wang Ruilan",
    "王璐": "Wang Lu",
    "王金凤": "Wang Jinfeng",
    "王阿贞": "Wang Azhen",
    "玛力亚木·玉素甫": "Maliyamu Yusufu",
    "田卫彬": "Tian Weibin",
    "石晓晨": "Shi Xiaochen",
    "胡寒冰": "Hu Hanbing",
    "董天操": "Dong Tiancao",
    "董彬彬": "Dong Binbin",
    "袁成斌": "Yuan Chengbin",
    "詹丽英": "Zhan Liying",
    "许董俊": "Xu Dongjun",
    "谈定玉": "Tan Dingyu",
    "谢云": "Xie Yun",
    "费丹婷": "Fei Danting",
    "赵文新": "Zhao Wenxin",
    "邓医宇": "Deng Yiyu",
    "邵义如": "Shao Yiru",
    "邹晓静": "Zou Xiaojing",
    "邹静蓉": "Zou Jingrong",
    "郁慧杰": "Yu Huijie",
    "陆俊杰": "Lu Junjie",
    "陈淼": "Chen Miao",
    "陈珵": "Chen Cheng",
    "陈雪梅": "Chen Xuemei",
    "顾天衡": "Gu Tianheng",
    "顾逸晨": "Gu Yichen",
    "高成金": "Gao Chengjin",
    "高霏": "Gao Fei",
    "丁海林": "Ding Hailin",
    "俞尧": "Yu Yao",
    "卢苏": "Lu Su",
    "周燕南": "Zhou Yannan",
    "徐斐翔": "Xu Feixiang",
    "曹一羽": "Cao Yiyu",
    "曹琪": "Cao Qi",
    "李飞": "Li Fei",
    "林梦娜": "Lin Mengna",
    "王学超": "Wang Xuechao",
    "田学": "Tian Xue",
    "薛明明": "Xue Mingming",
    "许世杰": "Xu Shijie",
    "邝中淑": "Kuang Zhongshu",
    "郑娜": "Zheng Na",
    "阙思瑾": "Que Sijin",
    "陈安书": "Chen Anshu",
    "陈玉梅": "Chen Yumei",
    "陈琛": "Chen Chen",
    "陈遥": "Chen Yao",
    "龙香宇": "Long Xiangyu",
    "何巧兰": "He Qiaolan",
    "刘方舟": "Liu Fangzhou",
    "吴宏玉": "Wu Hongyu",
    "周晴": "Zhou Qing",
    "常美佳": "Chang Meijia",
    "张雨婷": "Zhang Yuting",
    "杨依霖": "Yang Yilin",
    "林锴珺": "Lin Kaijun",
    "沈永琦": "Shen Yongqi",
    "罗悦": "Luo Yue",
    "袁莉": "Yuan Li",
    "邢玲玉": "Xing Lingyu",
    "姜宁": "Jiang Ning",
    "裘天颐": "Qiu Tianyi",
    "黄丽红": "Huang Lihong",
    "乔欣曼": "Qiao Xinman",
    "卢珍珍": "Lu Zhenzhen",
    "李文文": "Li Wenwen",
    "李浩": "Li Hao",
    "李秉哲": "Li Bingzhe",
    "梁斐": "Liang Fei",
    "王莹莹": "Wang Yingying",
    "邓欣然": "Deng Xinran",
    "陈晨鑫": "Chen Chenxin",
    "阮彤": "Ruan Tong",
    "陈磊": "Chen Lei",
    "曹子睿": "Cao Zirui",
    "曾研": "Zeng Yan",
  };

  const memberNameEntries = Object.entries(memberNames);

  const replacements = [
    ["血清生物标志物联合检测在急性呼吸窘迫综合征诊断和预后预测中的价值", "The value of combined serum biomarkers detection in the diagnosis and prognosis prediction of acute respiratory distress syndrome"],
    ["孙健、孙湛、杨依霖、宋振举、徐斐翔", "Sun Jian, Sun Zhan, Yang Yilin, Song Zhenju, Xu Feixiang"],
    ["中华急诊医学杂志", "Chinese Journal of Emergency Medicine"],
    ["中国脓毒症和 ARDS 临床研究协作联盟", "Chinese Sepsis and ARDS Clinical Research Collaborative Network"],
    ["SEpsis and ARDS Research Collaborative network of CHina", "SEpsis and ARDS Research Collaborative Network of China"],
    ["华中科技大学同济医学院附属协和医院", "Union Hospital, Tongji Medical College, Huazhong University of Science and Technology"],
    ["武汉大学人民医院", "Renmin Hospital of Wuhan University"],
    ["上海市第一人民医院", "Shanghai General Hospital"],
    ["同济大学附属第十人民医院", "Tenth People's Hospital of Tongji University"],
    ["上海交通大学医学院附属仁济医院", "Renji Hospital, Shanghai Jiao Tong University School of Medicine"],
    ["上海中医药大学附属曙光医院", "Shuguang Hospital, Shanghai University of Traditional Chinese Medicine"],
    ["同济大学附属东方医院", "Shanghai East Hospital, Tongji University"],
    ["上海交通大学医学院附属新华医院", "Xinhua Hospital, Shanghai Jiao Tong University School of Medicine"],
    ["公利医院", "Gongli Hospital"],
    ["复旦大学附属金山医院", "Jinshan Hospital, Fudan University"],
    ["复旦大学附属浦东医院", "Pudong Hospital, Fudan University"],
    ["复旦大学附属闵行医院", "Minhang Hospital, Fudan University"],
    ["上海市第四人民医院", "Shanghai Fourth People's Hospital"],
    ["浙江大学附属第二医院", "The Second Affiliated Hospital of Zhejiang University"],
    ["嘉兴市第一医院", "Jiaxing First Hospital"],
    ["福建省泉州市第一医院", "Quanzhou First Hospital, Fujian Province"],
    ["江苏省苏北人民医院", "Subei People's Hospital, Jiangsu"],
    ["南京医科大学附属无锡人民医院", "Wuxi People's Hospital, Nanjing Medical University"],
    ["无锡市惠山区人民医院", "Huishan People's Hospital, Wuxi"],
    ["宜兴市人民医院", "Yixing People's Hospital"],
    ["江阴市人民医院", "Jiangyin People's Hospital"],
    ["广东省人民医院", "Guangdong Provincial People's Hospital"],
    ["郑州大学第一附属医院", "The First Affiliated Hospital of Zhengzhou University"],
    ["急诊危重病科", "Emergency and Critical Care Medicine"],
    ["急诊科", "Emergency Medicine"],
    ["重症医学科副主任", "Deputy Director of Critical Care Medicine"],
    ["急危重病中心主任", "Director of the Emergency and Critical Care Center"],
    ["急诊科主任", "Director of Emergency Medicine"],
    ["科主任", "Department Director"],
    ["交大医学院", "Shanghai Jiao Tong University School of Medicine"],
    ["急危重病中心", "Emergency and Critical Care Center"],
    ["科副主任", "Deputy Director, Department"],
    ["行政副主任", "Administrative Deputy Director"],
    ["主任委员", "Committee Chair"],
    ["副主任委员", "Deputy Committee Chair"],
    ["医学博士", "MD"],
    ["博士后", "Postdoctoral fellow"],
    ["研究生导师", "graduate supervisor"],
    ["副教授", "Associate Professor"],
    ["硕导", "Master's supervisor"],
    ["主持工作", "acting director"],
    ["急诊医学科", "Emergency Medicine"],
    ["主中心团队", "Coordinating-center team"],
    ["查看团队成员", "View team members"],
    ["收起团队成员", "Collapse team members"],
    ["医生", "Physician"],
    ["博士", "PhD"],
    ["共同通讯作者", "Co-corresponding author"],
    ["并列通讯作者", "Co-corresponding author"],
    ["通讯作者", "Corresponding author"],
    ["重症医学科", "Critical Care Medicine"],
    ["急重症中心", "Emergency and Critical Care Center"],
    ["副主任医师", "Associate Chief Physician"],
    ["主任医师", "Chief Physician"],
    ["助理研究员", "Assistant Researcher"],
    ["医师", "Physician"],
    ["博士生导师", "Doctoral supervisor"],
    ["硕士研究生导师", "Master's supervisor"],
    ["访问学者", "Visiting scholar"],
    ["博导", "Doctoral supervisor"],
    ["教授", "Professor"],
    ["副主任", "Deputy Director"],
    ["主任", "Director"],
    ["国家自然科学基金", "National Natural Science Foundation of China"],
    ["国家重点研发计划", "National Key R&D Program"],
    ["发表论文", "published papers"],
    ["分中心 PI", "Branch-center PI"],
    ["主中心 PI", "Coordinating-center PI"],
    ["分中心", "Branch center"],
    ["主中心", "Coordinating center"],
    ["公开成员", "public members"],
    ["名公开成员", " public members"],
    ["团队成员", "team member"],
    ["查看中心成员", "View center members"],
    ["收起中心成员", "Collapse center members"],
    ["查看简介", "View profile"],
    ["数据截至", "Data as of"],
    ["科研合作", "research collaboration"],
    ["多中心协作", "multicenter coordination"],
    ["公开资料", "public information"],
    ["代表性论文", "selected publications"],
    ["代表成果", "selected evidence"],
    ["研究方向", "research direction"],
    ["研究问题", "research question"],
    ["研究方法", "methods"],
    ["研究目标", "research aim"],
    ["合作机构", "partner institutions"],
    ["协作机构", "partner institutions"],
    ["研究与成果", "Research & outcomes"],
    ["合作单位", "Partner centers"],
    ["队列信息", "Cohort"],
    ["项目文件", "Documents"],
    ["在线同步", "online synchronization"],
    ["静态数据", "static data"],
    ["统计年度", "years covered"],
    ["家中心", " centers"],
    ["篇成果", " selected papers"],
    ["篇", " papers"],
    ["份文件", " files"],
  ];

  replacements.sort((a, b) => b[0].length - a[0].length);

  const pageTitles = {
    "index.html": "SEARCH | Clinical Research Collaboration Network",
    "research.html": "Research & outcomes | SEARCH",
    "network.html": "Partner centers | SEARCH",
    "cohort.html": "Cohort | SEARCH",
    "documents.html": "Documents | SEARCH",
  };

  function pad(original, translated) {
    const leading = original.match(/^\s*/)?.[0] || "";
    const trailing = original.match(/\s*$/)?.[0] || "";
    return `${leading}${translated}${trailing}`;
  }

  function translateText(value) {
    const trimmed = value.trim();
    if (!trimmed || !/[\u3400-\u9fff]/.test(trimmed)) return value;
    let translated = exact[trimmed] || trimmed;
    memberNameEntries.forEach(([from, to]) => {
      translated = translated.split(from).join(to);
    });
    replacements.forEach(([from, to]) => {
      translated = translated.split(from).join(to);
    });
    return pad(value, translated);
  }

  function translateAttributes(element) {
    ["aria-label", "aria-valuetext", "alt", "title"].forEach((attribute) => {
      if (!element.hasAttribute(attribute)) return;
      element.__searchOriginalAttributes ||= {};
      if (!(attribute in element.__searchOriginalAttributes)) {
        element.__searchOriginalAttributes[attribute] = element.getAttribute(attribute);
      }
      const original = element.__searchOriginalAttributes[attribute];
      element.setAttribute(attribute, currentLanguage === "en" ? translateText(original) : original);
    });
  }

  function refresh() {
    if (refreshing) return;
    refreshing = true;
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    let node;
    while ((node = walker.nextNode())) {
      if (node.parentElement?.matches("script, style, noscript")) continue;
      if (node.__searchOriginalText === undefined) node.__searchOriginalText = node.nodeValue;
      const original = node.__searchOriginalText;
      node.nodeValue = currentLanguage === "en" ? translateText(original) : original;
    }
    document.querySelectorAll("*").forEach(translateAttributes);
    refreshing = false;
  }

  function updatePageMeta() {
    const description = document.querySelector('meta[name="description"]');
    if (description) description.__searchOriginalDescription ||= description.content;
    if (currentLanguage !== "en") {
      document.title = originalTitle;
      if (description) description.content = description.__searchOriginalDescription;
      return;
    }
    const file = window.location.pathname.split("/").pop() || "index.html";
    document.title = pageTitles[file] || "SEARCH | Clinical Research Collaboration Network";
    if (description) description.content = "English research portal for the SEARCH multicenter ARDS and sepsis clinical research network.";
  }

  function updateLanguageButton() {
    if (!languageButton) return;
    languageButton.textContent = "中文 / EN";
    languageButton.setAttribute("aria-pressed", currentLanguage === "en" ? "true" : "false");
    languageButton.title = currentLanguage === "en" ? "Switch to Chinese" : "切换至 English";
    languageButton.setAttribute("aria-label", currentLanguage === "en" ? "Switch language to Chinese" : "切换至 English");
  }

  function setLanguage(language, persist = true) {
    currentLanguage = language === "en" ? "en" : "zh-CN";
    root.lang = currentLanguage;
    refresh();
    updatePageMeta();
    updateLanguageButton();
    if (persist) {
      try {
        localStorage.setItem("search-showcase-lang", currentLanguage);
      } catch (_) {
        // Local preference is optional.
      }
    }
    window.dispatchEvent(new CustomEvent("search-language-change", { detail: { language: currentLanguage } }));
  }

  function storedLanguage() {
    try {
      const saved = localStorage.getItem("search-showcase-lang");
      if (saved === "en" || saved === "zh-CN") return saved;
    } catch (_) {
      // Continue with the browser preference.
    }
    return navigator.language?.toLowerCase().startsWith("en") ? "en" : "zh-CN";
  }

  languageButton?.addEventListener("click", () => setLanguage(currentLanguage === "en" ? "zh-CN" : "en"));

  nav?.querySelectorAll("a").forEach((link) => {
    link.addEventListener("click", () => {
      nav.classList.remove("is-open");
      navToggle?.setAttribute("aria-expanded", "false");
    });
  });

  const observer = new MutationObserver(() => {
    if (currentLanguage === "en" && !refreshing) refresh();
  });
  observer.observe(document.body, { childList: true, subtree: true });

  setLanguage(storedLanguage(), false);
})();
